import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Position from "@/components/Position";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body
                style={{ position: "relative", display: "flex", flexDirection: "column" }}
                suppressHydrationWarning={true}
            >
                <Theme>
                    <div className="h-16 flex flex-row-reverse items-center gap-3  px-4">
                        <h3 className="scroll-m-20 text-2xl  font-semibold tracking-tight ">
                            湖北国际物流机场塔台执勤系统
                        </h3>
                        <div className="scroll-m-20 text-2xl font-semibold tracking-tight ">
                            <Position />
                        </div>
                    </div>
                    <div className="flex flex-row flex-1">
                        <nav className="w-40   ">
                            <ul className="flex flex-col gap-2 px-2 ">
                                <li className="text-black font-semibold">
                                    <a href="/">主页</a>
                                </li>
                                <li>
                                    <a href="/prepare">岗前准备</a>
                                </li>
                                <li>
                                    <a href="/shift">交接班</a>
                                </li>
                                <li>
                                    <a href="/admin">后台</a>
                                </li>
                            </ul>
                        </nav>
                        <div className=" relative flex-1">{children}</div>
                    </div>
                </Theme>
            </body>
        </html>
    );
}
