module.exports= [
    {
      "id": 0,
      "name": "姓名",
      "sex": "性别",
      "personalPhone": "个人电话",
      "companyPhone": "公司电话",
      "emergencyPhone": "紧急联系电话",
      "address": "住址",
      "workYear": "工龄",
      "entryDate": "入职时间",
      "contractID": "合同编号",
      "job": "职务",
      "permissions": "权限",
      "email": "邮箱",
      "avatar": "头像"
    },
    {
      "id": 1,
      "name": "吴莉",
      "sex": "女",
      "personalPhone": 13316898783,
      "companyPhone": 13828733276,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 20,
      "entryDate": "",
      "contractID": "",
      "job": "总经理",
      "permissions": "",
      "email": "lily18ekev.net,cn",
      "avatar": ""
    },
    {
      "id": 2,
      "name": "吴笛",
      "sex": "女",
      "personalPhone": 18929395172,
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "总监",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 3,
      "name": "罗旭航",
      "sex": "男",
      "personalPhone": 13620967835,
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 1,
      "entryDate": "",
      "contractID": "",
      "job": "财务",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 4,
      "name": "张大海",
      "sex": "男",
      "personalPhone": 13691754651,
      "companyPhone": 18126523870,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 10,
      "entryDate": "",
      "contractID": "",
      "job": "商务",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 5,
      "name": "王娟娟",
      "sex": "女",
      "personalPhone": 13923712636,
      "companyPhone": 17722639724,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "商务",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 6,
      "name": "崔小荣",
      "sex": "女",
      "personalPhone": 13267044507,
      "companyPhone": 18926069499,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "商务",
      "permissions": "",
      "email": "lily15@kev.net.cn",
      "avatar": ""
    },
    {
      "id": 7,
      "name": "周芬",
      "sex": "女",
      "personalPhone": 13728700221,
      "companyPhone": 18926069499,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "商务",
      "permissions": "",
      "email": "lily17@key.net.cn",
      "avatar": ""
    },
    {
      "id": 8,
      "name": "张明圆",
      "sex": "女",
      "personalPhone": 15827600632,
      "companyPhone": 15302755267,
      "emergencyPhone": "",
      "address": "深圳",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "商务",
      "permissions": "",
      "email": "lily19@kev,net.cn",
      "avatar": ""
    },
    {
      "id": 9,
      "name": "刘海",
      "sex": "男",
      "personalPhone": 18988711669,
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "东莞",
      "age": 30,
      "workYear": 20,
      "entryDate": "",
      "contractID": "",
      "job": "厂长",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 10,
      "name": "付及梅",
      "sex": "女",
      "personalPhone": "13544743979#18274667831",
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "东莞",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "品管",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 11,
      "name": "黄宜威",
      "sex": "男",
      "personalPhone": 13631681136,
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "东莞",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "工程",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 12,
      "name": "王世昌",
      "sex": "男",
      "personalPhone": 13272214765,
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "东莞",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "工程",
      "permissions": "",
      "email": "",
      "avatar": ""
    },
    {
      "id": 13,
      "name": "黄从东",
      "sex": "男",
      "personalPhone": "1501s6946025",
      "companyPhone": "",
      "emergencyPhone": "",
      "address": "东莞",
      "age": 30,
      "workYear": 5,
      "entryDate": "",
      "contractID": "",
      "job": "工程",
      "permissions": "",
      "email": "",
      "avatar": ""
    }
  ]